# Generated by Django 2.1.1 on 2018-09-28 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('thumbnail', models.ImageField(default='null', upload_to='media')),
                ('postTag', models.CharField(default='general', max_length=200)),
                ('created_by_name', models.CharField(default='system', max_length=200)),
                ('claps_number', models.BigIntegerField(default='0')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_label', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(default=0, on_delete='CASCADE', to='posts.Tag'),
        ),
    ]
