# Generated by Django 2.1.1 on 2018-09-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180928_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedByEditors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete='CASCADE', to='posts.Posts')),
            ],
        ),
    ]
