# Generated by Django 2.1.1 on 2018-09-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180928_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
