# Generated by Django 2.1.1 on 2018-09-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_posts_is_nsfw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(default=0, on_delete='CASCADE', to='posts.Posts')),
            ],
        ),
    ]
