# Generated by Django 2.1.1 on 2018-09-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_recommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=300)),
                ('site_description', models.CharField(max_length=300)),
                ('site_logo', models.ImageField(default='null', upload_to='media')),
                ('show_nsfw_posts_without_asking', models.BooleanField(default=False)),
            ],
        ),
    ]
