# Generated by Django 2.1.1 on 2018-09-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20180928_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_settings',
            name='site_status_is_production',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], max_length=300),
        ),
    ]
