# Generated by Django 2.1.1 on 2018-09-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20180929_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delete_requested',
            options={'verbose_name_plural': 'Delete Requested'},
        ),
        migrations.AddField(
            model_name='delete_requested',
            name='user_comment',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
