# Generated by Django 2.1.1 on 2018-09-30 03:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20180929_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='total_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='delete_requested',
            name='post',
            field=models.ForeignKey(help_text=' ', on_delete=django.db.models.deletion.CASCADE, to='posts.Posts'),
        ),
        migrations.AlterField(
            model_name='delete_requested',
            name='reason_for_request',
            field=models.CharField(choices=[('Discriminatory', 'Discriminatory'), ('Offensive', 'Offensive'), ('Blackmail', 'Blackmail')], help_text=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=models.TextField(help_text=' '),
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ManyToManyField(help_text=' ', to='posts.Tag'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text=' '),
        ),
        migrations.AlterField(
            model_name='posts',
            name='thumbnail',
            field=models.ImageField(default='null', help_text=' ', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(help_text=' ', max_length=200),
        ),
    ]
