# Generated by Django 2.1.1 on 2018-10-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20181004_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestATopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=300)),
                ('bigger_description', models.CharField(blank=True, default='leave blank unless you are compelled', max_length=300)),
                ('your_name', models.CharField(blank=True, default='Leave blank unless you want some credit (:', max_length=300)),
            ],
        ),
    ]
